"""add enum to posts

Revision ID: 5d459f653ebf
Revises: 3d77fc1608eb
Create Date: 2025-03-20 16:33:44.516319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d459f653ebf'
down_revision = '3d77fc1608eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.Enum('ILLUSTRATION', 'NOVEL', 'MANGA', name='posttype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_type')

    # ### end Alembic commands ###
