"""add enum to user + date joined

Revision ID: 7370cd1ca779
Revises: 5d459f653ebf
Create Date: 2025-03-20 16:38:30.242581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7370cd1ca779'
down_revision = '5d459f653ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('ARTIST', 'MODERATOR', name='role'), nullable=False))
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_joined')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
