"""Added cascades and relationships

Revision ID: fd3ab3d0740c
Revises: 
Create Date: 2025-04-07 22:59:38.829362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3ab3d0740c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_author_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('comments_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('follows_follower_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follows_followed_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['followed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint('images_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('likes_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint('post_tags_tag_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('post_tags_post_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint('reports_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reports_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint('saved_posts_post_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('saved_posts_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'posts', ['post_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_tags', schema=None) as batch_op:
        batch_op.drop_constraint('user_tags_tag_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_tags_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_tags_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_tags_tag_id_fkey', 'tags', ['tag_id'], ['id'])

    with op.batch_alter_table('saved_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('saved_posts_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('saved_posts_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reports_author_id_fkey', 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key('reports_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_author_id_fkey', 'users', ['author_id'], ['id'])

    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_tags_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('post_tags_tag_id_fkey', 'tags', ['tag_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('likes_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('images_post_id_fkey', 'posts', ['post_id'], ['id'])

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follows_followed_id_fkey', 'users', ['followed_id'], ['id'])
        batch_op.create_foreign_key('follows_follower_id_fkey', 'users', ['follower_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_post_id_fkey', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('comments_author_id_fkey', 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
